### PR TITLE
Update project_patch.rb

### PR DESCRIPTION
**Pull request by zerodeux**
Redmine 3.0 compat

### CODE REVIEW

**Comment by a1exsh** [comment]
Thanks, merged.  Does it start with 3.0 without any changes to init.rb, by the way?

**Comment by zerodeux** [comment]
On 13/10/15 21:43, a1exsh wrote:
> Thanks, merged. Does it start with 3.0 without any changes to init.rb,
> by the way?

  It does start, but it fails with other errors which I didn't solve :(

  Eg:

    Started GET "/canned_responses" for 88.162.75.225 at 2015-10-13
21:51:55 +0200
    Processing by CannedResponsesController#index as HTML
      Current user: admin (id=1)
    Completed 500 Internal Server Error in 5ms

    NoMethodError (undefined method `global?' for
#<Class:0x00000003e5e5b8>):
      activerecord (4.2.0) lib/active_record/dynamic_matchers.rb:26:in
`method_missing'

plugins/redmine_canned_responses/app/controllers/canned_responses_controller.rb:80:in
`find_project'
      activesupport (4.2.0) lib/active_support/callbacks.rb:427:in
`block in make_lambda'
      activesupport (4.2.0) lib/active_support/callbacks.rb:163:in `call'

**Comment by a1exsh** [comment]
A-ha, that's not very nice.  I'll have a look.

**Comment by a1exsh** [comment]
Please see branch 3.0

**Comment by zerodeux** [comment]
On 14/10/15 20:22, a1exsh wrote:
> Please see branch 3.0

  Tried, fails at rake redmine:plugins:migrate time :

    ArgumentError: Unknown key: :order. Valid keys are: :class_name,
:class, :foreign_key, :validate, :autosave, :table_name, :before_add,
:after_add, :before_remove, :after_remove, :extend, :primary_key,
:dependent, :as, :through, :source, :source_type, :inverse_of,
:counter_cache, :join_table, :foreign_type

/var/www/demo/gem/gems/activesupport-4.2.0/lib/active_support/core_ext/hash/keys.rb:75:in
`block in assert_valid_keys'

/var/www/demo/gem/gems/activesupport-4.2.0/lib/active_support/core_ext/hash/keys.rb:73:in
`each_key'

/var/www/demo/gem/gems/activesupport-4.2.0/lib/active_support/core_ext/hash/keys.rb:73:in
`assert_valid_keys'

/var/www/demo/gem/gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:82:in
`validate_options'

/var/www/demo/gem/gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:62:in
`initialize'

/var/www/demo/gem/gems/activerecord-4.2.0/lib/active_record/associations/builder/collection_association.rb:18:in
`initialize'

/var/www/demo/gem/gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:47:in
`new'

/var/www/demo/gem/gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:47:in
`create_builder'

/var/www/demo/gem/gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:35:in
`build'

/var/www/demo/gem/gems/activerecord-4.2.0/lib/active_record/associations.rb:1258:in
`has_many'

/var/www/demo/redmine/plugins/redmine_canned_responses/lib/redmine_canned_responses/project_patch.rb:7:in
`block in included'

/var/www/demo/redmine/plugins/redmine_canned_responses/lib/redmine_canned_responses/project_patch.rb:6:in
`class_eval'

/var/www/demo/redmine/plugins/redmine_canned_responses/lib/redmine_canned_responses/project_patch.rb:6:in
`included'

**Comment by zerodeux** [comment]
On 15/10/15 13:30, Vincent Caron wrote:
>   Tried, fails at rake redmine:plugins:migrate time :

  Oh my bad, I accidentally deployed the master branch again. 3.0 branch
installs fine, testing now the functionnality.

**Comment by zerodeux** [comment]
Testing branch 3.0 against Redmine 3.0.4 : while configuring a
projects's canned responses at /projects/<id>/canned_responses, I fail
to add a canned response with this error in a flash :

* Title must be filled in
* Text filed must be filled in

... altough I did filled them in. Log is :

    Started POST "/projects/projet-de-test/canned_responses" for
80.215.234.175 at 2015-10-15 13:40:04 +0200
    Processing by CannedResponsesController#create as HTML
      Parameters: {"utf8"=>"✓",
"authenticity_token"=>"ZUmKJ09UOiJulJtcwude0opAl0fNc5r+tfyojRMuWWKJ/2XQGBIiYomzi2DzuMIirEXPnM4XKcvT3BOEjjbHvw==",
"project_id"=>"projet-de-test", "canned_response"=>{"title"=>"DTC",
"text"=>"<p>Nous vous proposons de vous mettre votre demande dans votre
fondement.</p>\r\n"}, "commit"=>"Sauvegarder"}
      Current user: admin (id=1)
    WARNING: Can't mass-assign protected attributes for CannedResponse:
title, text

      Rendered
plugins/redmine_canned_responses/app/views/canned_responses/_form.html.erb
(5.3ms)
      Rendered
plugins/redmine_canned_responses/app/views/canned_responses/new.html.erb
within layouts/base (5.7ms)
      Rendered
plugins/redmine_canned_responses/app/views/hooks/_canned_responses_stylesheet.erb
(0.3ms)
      Rendered
plugins/redmine_create_wiki_page/app/views/create_wiki_page/_init_create_wiki_page.erb
(0.1ms)
      Rendered
plugins/redmine_wiki_extensions/app/views/wiki_extensions/_html_header.html.erb
(2.0ms)
      Rendered
plugins/redmine_wiki_extensions/app/views/wiki_extensions/_body_bottom.html.erb
(0.4ms)
    Completed 200 OK in 122ms (Views: 110.6ms | ActiveRecord: 2.1ms)

**Comment by a1exsh** [comment]
Works for me on redmine 3.0.5-stable.  Are you sure you've restarted the instance after switching the plugin code?

**Comment by zerodeux** [comment]
On 15/10/15 14:32, a1exsh wrote:
> Works for me on redmine 3.0.5-stable. Are you sure you've restarted the
> instance after switching the plugin code?

  I'm actually on 3.0.1.stable. Yes, I've restarted the Rails app.

**Pull request merged**
